{
  "openapi": "3.1.0",
  "info": {
    "version": "1.0.0",
    "title": "Leleka App",
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "description": "This is a documentation of Leleka App"
  },
  "servers": [
    {
      "url": "https://gitpub-backend-qq3d.onrender.com",
      "description": "Production server"
    },
    {
      "url": "http://localhost:3000",
      "description": "Local development server"
    }
  ],
  "tags": [
    {
      "name": "Auth",
      "description": "Auth operations"
    },
    {
      "name": "Diaries",
      "description": "Diary operations."
    }
  ],
  "paths": {
    "/api/auth/register": {
      "post": {
        "tags": [
          "Auth"
        ],
        "summary": "Register user",
        "operationId": "registerUser",
        "description": "Register a new user",
        "security": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "name",
                  "email",
                  "password"
                ],
                "properties": {
                  "name": {
                    "type": "string",
                    "example": "John Doe"
                  },
                  "email": {
                    "type": "string",
                    "format": "email",
                    "example": "john@example.com"
                  },
                  "password": {
                    "type": "string",
                    "minLength": 8,
                    "example": "StrongPass123!"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "User successfully registered",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "integer",
                      "example": 201
                    },
                    "message": {
                      "type": "string",
                      "example": "Successfully registered a user!"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "string",
                          "example": "64adf5e8b3f9a27f9c11d3b4"
                        },
                        "name": {
                          "type": "string",
                          "example": "Igor"
                        },
                        "email": {
                          "type": "string",
                          "format": "email",
                          "example": "igor@example.com"
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/400"
          }
        }
      }
    },
    "/api/auth/login": {
      "post": {
        "tags": [
          "Auth"
        ],
        "summary": "Login user",
        "operationId": "loginUser",
        "description": "Login user with email and password",
        "security": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "email",
                  "password"
                ],
                "properties": {
                  "email": {
                    "type": "string",
                    "format": "email",
                    "example": "john@example.com"
                  },
                  "password": {
                    "type": "string",
                    "example": "StrongPass123!"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "User successfully logged in",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "integer",
                      "example": 200
                    },
                    "message": {
                      "type": "string",
                      "example": "Successfully logged in an user!"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "accessToken": {
                          "type": "string",
                          "example": "eyJhbGciOiJIUzI1NiIsInR..."
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "$ref": "#/components/responses/401"
          }
        }
      }
    },
    "/api/auth/logout": {
      "post": {
        "tags": [
          "Auth"
        ],
        "summary": "Logout user",
        "operationId": "logoutUser",
        "description": "Logout user and clear cookies",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "204": {
            "description": "Successfully logged out (No content)"
          },
          "401": {
            "$ref": "#/components/responses/401"
          }
        }
      }
    },
    "/api/diaries": {
      "get": {
        "tags": [
          "Diaries"
        ],
        "summary": "Get user diaries",
        "operationId": "getUserDiaries",
        "description": "Returns all diaries for the authenticated user.",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "$ref": "#/components/responses/200"
          },
          "401": {
            "$ref": "#/components/responses/401"
          },
          "500": {
            "$ref": "#/components/responses/500"
          }
        }
      },
      "post": {
        "tags": [
          "Diaries"
        ],
        "summary": "Create new diary entry",
        "operationId": "createDiary",
        "description": "Creates a new diary entry for the authenticated user.",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "title",
                  "description",
                  "date",
                  "emotions"
                ],
                "properties": {
                  "title": {
                    "type": "string",
                    "example": "First baby kick"
                  },
                  "description": {
                    "type": "string",
                    "example": "Today I felt the gentle kicks - it as incredible!"
                  },
                  "date": {
                    "type": "string",
                    "format": "date",
                    "example": "2025-09-20"
                  },
                  "emotions": {
                    "type": "array",
                    "items": {
                      "type": "string",
                      "description": "Emotion ObjectId",
                      "example": "6895bd86a5c677999ed2ae2c"
                    }
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "$ref": "#/components/responses/201"
          },
          "400": {
            "$ref": "#/components/responses/400"
          },
          "401": {
            "$ref": "#/components/responses/401"
          },
          "500": {
            "$ref": "#/components/responses/500"
          }
        }
      }
    },
    "/api/diaries/{diaryId}": {
      "patch": {
        "tags": [
          "Diaries"
        ],
        "summary": "Update diary entry",
        "operationId": "updateDiary",
        "description": "Update a diary entry for the authenticated user.",
        "parameters": [
          {
            "in": "path",
            "name": "diaryId",
            "required": true,
            "description": "Diary ID to update",
            "schema": {
              "type": "string",
              "example": "68cd804b54ecfa2d01635545"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/DiaryUpdate"
              },
              "example": {
                "title": "Updated entry: Doctors visit",
                "description": "Added the ultrasound results, doctor said everything looks great!",
                "date": "2025-09-20",
                "emotions": [
                  "6895bd86a5c677999ed2ae27"
                ]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successfully updated diary!",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "integer",
                      "example": 200
                    },
                    "message": {
                      "type": "string",
                      "example": "Successfully updated diary!"
                    },
                    "data": {
                      "$ref": "#/components/schemas/Diary"
                    }
                  }
                },
                "example": {
                  "status": 200,
                  "message": "Successfully updated diary!",
                  "data": {
                    "_id": "68cc61d870990cf24572f399",
                    "title": "Updated entry: Doctors visit",
                    "description": "Added the ultrasound results, doctor said everything looks great!",
                    "date": "2025-09-20",
                    "emotions": [
                      "6895bd86a5c677999ed2ae27",
                      "6895bd86a5c677999ed2ae16"
                    ],
                    "userId": "68cc619370990cf24572f395",
                    "createdAt": "2025-09-19T17:21:36.199Z",
                    "updatedAt": "2025-09-19T17:31:10.199Z"
                  }
                }
              }
            }
          },
          "401": {
            "$ref": "#/components/responses/401"
          },
          "404": {
            "$ref": "#/components/responses/404"
          },
          "500": {
            "$ref": "#/components/responses/500"
          }
        }
      },
      "delete": {
        "tags": [
          "Diaries"
        ],
        "summary": "Delete diary",
        "operationId": "deletedDiary",
        "description": "Delete diary for the authenticated user.",
        "parameters": [
          {
            "in": "path",
            "name": "diaryId",
            "required": true,
            "description": "Diary ID to delete",
            "schema": {
              "type": "string",
              "example": "68cd628bab0811759b9d8226"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successfully deleted diary entry!",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "integer",
                      "example": 200
                    },
                    "message": {
                      "type": "string",
                      "example": "Successfully deleted diary entry!"
                    },
                    "data": {
                      "$ref": "#/components/schemas/Diary"
                    }
                  }
                },
                "examples": {
                  "created": {
                    "value": {
                      "status": 200,
                      "message": "Successfully delete diary entry!",
                      "data": {
                        "_id": "68cd804b54ecfa2d01635545",
                        "title": "Moments with you",
                        "description": "You are still so small, yet my whole life already revolves around you.",
                        "date": "2025-09-20T00:00:00.000Z",
                        "emotions": [
                          "6895bd86a5c677999ed2ae17",
                          "6895bd86a5c677999ed2ae30"
                        ],
                        "userId": "68cc2d4187e54afd6273db2",
                        "createdAt": "2025-09-19T16:09:47.277Z",
                        "updatedAt": "2025-09-19T16:09:47.277Z"
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "$ref": "#/components/responses/401"
          },
          "404": {
            "$ref": "#/components/responses/404"
          },
          "500": {
            "$ref": "#/components/responses/500"
          }
        }
      }
    },
    "/api/weeks/current": {
      "get": {
        "tags": [
          "Weeks"
        ],
        "summary": "Отримати поточний тиждень (приватна версія)",
        "operationId": "getCurrentWeekData",
        "description": "Повертає дані про поточний тиждень вагітності на основі переданої дати пологів (`dueDate`). Ендпоінт вимагає авторизації.\n",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "dueDate",
            "in": "query",
            "required": true,
            "description": "Дата передбачуваних пологів (формат YYYY-MM-DD)",
            "schema": {
              "type": "string",
              "format": "date",
              "example": "2025-12-19"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Успішна відповідь",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "week": {
                      "type": "integer",
                      "example": 28
                    },
                    "daysToDue": {
                      "type": "integer",
                      "example": 89
                    },
                    "pack": {
                      "$ref": "#/components/schemas/Pack"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/400"
          },
          "401": {
            "$ref": "#/components/responses/401"
          },
          "500": {
            "$ref": "#/components/responses/500"
          }
        }
      }
    },
    "/api/weeks/current/public": {
      "get": {
        "tags": [
          "Weeks"
        ],
        "summary": "Отримати поточний тиждень (публічна версія)",
        "operationId": "getCurrentWeekDataPublic",
        "description": "Повертає дані про поточний тиждень вагітності, включно з інформацією про розвиток дитини та відчуття мами. Публічний ендпоінт.\n",
        "security": [],
        "responses": {
          "200": {
            "description": "Успішна відповідь",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "week": {
                      "type": "integer",
                      "example": 5
                    },
                    "daysToDue": {
                      "type": "integer",
                      "example": 252
                    },
                    "pack": {
                      "$ref": "#/components/schemas/Pack"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "$ref": "#/components/responses/401"
          }
        }
      }
    },
    "/api/weeks/{weekNumber}": {
      "get": {
        "tags": [
          "Weeks"
        ],
        "summary": "Отримати дані по конкретному тижню",
        "operationId": "getWeekMomBabyData",
        "description": "Повертає детальну інформацію про розвиток дитини та стан мами для конкретного тижня вагітності.\n",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "weekNumber",
            "in": "path",
            "required": true,
            "description": "Номер тижня (1–40)",
            "schema": {
              "type": "integer",
              "minimum": 1,
              "maximum": 40,
              "example": 12
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Успішна відповідь",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "week": {
                      "type": "integer",
                      "example": 12
                    },
                    "baby": {
                      "$ref": "#/components/schemas/Baby"
                    },
                    "mom": {
                      "$ref": "#/components/schemas/Mom"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/400"
          },
          "404": {
            "$ref": "#/components/responses/404-2"
          },
          "500": {
            "$ref": "#/components/responses/500"
          }
        }
      }
    },
    "/api/weeks/{weekNumber}/mom": {
      "get": {
        "tags": [
          "Weeks"
        ],
        "summary": "Отримати дані про маму для конкретного тижня",
        "operationId": "getWeekMomData",
        "description": "Повертає інформацію про стан мами та поради для певного тижня вагітності.\n",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "weekNumber",
            "required": true,
            "schema": {
              "type": "integer"
            },
            "description": "Номер тижня вагітності"
          }
        ],
        "responses": {
          "200": {
            "description": "Дані для мами",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "week": {
                      "type": "integer",
                      "example": 12
                    },
                    "mom": {
                      "$ref": "#/components/schemas/mom"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "$ref": "#/components/responses/401"
          }
        }
      }
    },
    "/api/weeks/{weekNumber}/baby": {
      "get": {
        "tags": [
          "Weeks"
        ],
        "summary": "Отримати дані про дитину для конкретного тижня",
        "operationId": "getWeekBabyData",
        "description": "Повертає інформацію про розвиток дитини для певного тижня вагітності.\n",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "weekNumber",
            "required": true,
            "schema": {
              "type": "integer"
            },
            "description": "Номер тижня вагітності"
          }
        ],
        "responses": {
          "200": {
            "description": "Дані для дитини",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "week": {
                      "type": "integer",
                      "example": 12
                    },
                    "baby": {
                      "$ref": "#/components/schemas/baby"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "$ref": "#/components/responses/401"
          }
        }
      }
    }
  },
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer"
      }
    },
    "schemas": {
      "Diary": {
        "type": "object",
        "required": [
          "_id",
          "title",
          "description",
          "emotions",
          "userId"
        ],
        "properties": {
          "_id": {
            "type": "string",
            "description": "Diary id",
            "example": "68cc61d870990cf24572f399"
          },
          "title": {
            "type": "string",
            "description": "Title of notes in your diary",
            "example": "First hi!"
          },
          "description": {
            "type": "string",
            "description": "Write what's on your mind",
            "example": "It happened! First touchdown."
          },
          "date": {
            "type": "string",
            "format": "date",
            "description": "When user created note in diary",
            "example": "2025-01-28"
          },
          "emotions": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "_id": {
                  "type": "string",
                  "description": "Emotion ID",
                  "example": "6895bd86a5c677999ed2ae18"
                },
                "title": {
                  "type": "string",
                  "description": "Emotion title",
                  "example": "Гармонія"
                }
              }
            }
          },
          "userId": {
            "type": "string",
            "description": "Owner of the diary entry",
            "properties": {
              "_id": {
                "type": "string",
                "example": "68cc619370990cf24572f395"
              },
              "name": {
                "type": "string",
                "example": "Vikky"
              }
            }
          },
          "createdAt": {
            "type": "string",
            "format": "date-time",
            "readOnly": true,
            "example": "2025-09-19T14:02:51.012Z"
          },
          "updatedAt": {
            "type": "string",
            "format": "date-time",
            "readOnly": true,
            "example": "2025-09-19T14:02:51.012Z"
          }
        }
      },
      "DiaryUpdate": {
        "type": "object",
        "properties": {
          "title": {
            "type": "string",
            "example": "Doctors visit update"
          },
          "description": {
            "type": "string",
            "example": "Had an ultrasound today, the baby is growing well and everything looks perfect!"
          },
          "date": {
            "type": "string",
            "format": "date",
            "example": "2025-09-20"
          },
          "emotions": {
            "type": "array",
            "items": {
              "type": "string",
              "description": "Emotion ObjectId",
              "example": "6895bd86a5c677999ed2ae17"
            }
          }
        }
      },
      "Baby": {
        "type": "object",
        "properties": {
          "_id": {
            "type": "string",
            "example": "6895ce04a5c677999ed2af29"
          },
          "analogy": {
            "type": "string",
            "example": "Насінина кунжуту"
          },
          "weekNumber": {
            "type": "integer",
            "example": 5
          },
          "babySize": {
            "type": "number",
            "example": 0.3
          },
          "babyWeight": {
            "type": "number",
            "example": 0.2
          },
          "image": {
            "type": "string",
            "format": "uri",
            "example": "https://ftp.goit.study/img/lehlehka/6895ce04a5c677999ed2af29.webp"
          },
          "babyActivity": {
            "type": "string",
            "example": "Найголовніша подія тижня — починає битися крихітне серце!"
          },
          "babyDevelopment": {
            "type": "string"
          },
          "interestingFact": {
            "type": "string"
          },
          "momDailyTips": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      },
      "Mom": {
        "type": "object",
        "properties": {
          "_id": {
            "type": "string",
            "example": "6895cb58a5c677999ed2aefd"
          },
          "weekNumber": {
            "type": "integer",
            "example": 5
          },
          "feelings": {
            "type": "object",
            "properties": {
              "states": {
                "type": "array",
                "items": {
                  "type": "string"
                },
                "example": [
                  "Нудота",
                  "Часте сечовипускання",
                  "Емоційні гойдалки"
                ]
              },
              "sensationDescr": {
                "type": "string"
              }
            }
          },
          "comfortTips": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "category": {
                  "type": "string"
                },
                "tip": {
                  "type": "string"
                }
              }
            }
          }
        }
      },
      "Pack": {
        "type": "object",
        "properties": {
          "week": {
            "type": "integer",
            "example": 5
          },
          "baby": {
            "$ref": "#/components/schemas/Baby"
          },
          "mom": {
            "$ref": "#/components/schemas/Mom"
          }
        }
      },
      "mom": {
        "type": "object",
        "properties": {
          "_id": {
            "type": "string",
            "example": "6895cb58a5c677999ed2aefd"
          },
          "weekNumber": {
            "type": "integer",
            "example": 5
          },
          "feelings": {
            "type": "object",
            "properties": {
              "states": {
                "type": "array",
                "items": {
                  "type": "string"
                },
                "example": [
                  "Нудота",
                  "Часте сечовипускання",
                  "Емоційні гойдалки"
                ]
              },
              "sensationDescr": {
                "type": "string"
              }
            }
          },
          "comfortTips": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "category": {
                  "type": "string"
                },
                "tip": {
                  "type": "string"
                }
              }
            }
          }
        }
      },
      "baby": {
        "type": "object",
        "properties": {
          "_id": {
            "type": "string",
            "example": "6895ce04a5c677999ed2af29"
          },
          "analogy": {
            "type": "string",
            "example": "Насінина кунжуту"
          },
          "weekNumber": {
            "type": "integer",
            "example": 5
          },
          "babySize": {
            "type": "number",
            "example": 0.3
          },
          "babyWeight": {
            "type": "number",
            "example": 0.2
          },
          "image": {
            "type": "string",
            "format": "uri",
            "example": "https://ftp.goit.study/img/lehlehka/6895ce04a5c677999ed2af29.webp"
          },
          "babyActivity": {
            "type": "string",
            "example": "Найголовніша подія тижня — починає битися крихітне серце!"
          },
          "babyDevelopment": {
            "type": "string"
          },
          "interestingFact": {
            "type": "string"
          },
          "momDailyTips": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      }
    },
    "responses": {
      "200": {
        "description": "Successfully retrieved diaries!",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "required": [
                "status",
                "message",
                "data"
              ],
              "properties": {
                "status": {
                  "type": "integer",
                  "example": 200
                },
                "message": {
                  "type": "string",
                  "example": "Successfully created diary entry!"
                },
                "data": {
                  "$ref": "#/components/schemas/Diary"
                }
              }
            },
            "example": {
              "success": {
                "value": {
                  "status": 200,
                  "message": "Successfully retrieved diaries!",
                  "data": {
                    "_id": "68cd5f5e5470921c87d71748",
                    "title": "A piece of my heart",
                    "description": "You are still so small, yet my whole life already revolves around you.",
                    "data": "2025-09-20T00:00:00.000Z"
                  },
                  "emotions": [
                    {
                      "_id": "6895bd86a5c677999ed2ae2c",
                      "title": "Гармонія"
                    },
                    {
                      "_id": "6895bd86a5c677999ed2ae27",
                      "title": "Врівноваженість"
                    }
                  ],
                  "userId": {
                    "_id": "68cc2d6e187e54afd6273db6",
                    "name": "Vikky",
                    "email": "test1@gmail.com"
                  },
                  "createdAt": "2025-09-19T13:49:18.965Z",
                  "updatedAt": "2025-09-19T13:49:18.965Z"
                }
              }
            }
          }
        }
      },
      "201": {
        "description": "Successfully creates diary entry!",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "required": [
                "status",
                "message",
                "data"
              ],
              "properties": {
                "status": {
                  "type": "integer",
                  "example": 201
                },
                "message": {
                  "type": "string",
                  "example": "Successfully creates diary entry!"
                },
                "data": {
                  "$ref": "#/components/schemas/Diary"
                }
              }
            },
            "examples": {
              "created": {
                "value": {
                  "status": 201,
                  "message": "Successfully creates diary entry!",
                  "data": {
                    "_id": "68cd804b54ecfa2d01635545",
                    "title": "Moments with you",
                    "description": "You are still so small, yet my whole life already revolves around you.",
                    "date": "2025-09-20T00:00:00.000Z",
                    "emotions": [
                      "6895bd86a5c677999ed2ae17",
                      "6895bd86a5c677999ed2ae30"
                    ],
                    "userId": "68cc2d4187e54afd6273db2",
                    "id": "68cd804b54ecfa2d01635545",
                    "createdAt": "2025-09-19T16:09:47.277Z",
                    "updatedAt": "2025-09-19T16:09:47.277Z"
                  }
                }
              }
            }
          }
        }
      },
      "400": {
        "description": "Bad Request",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "required": [
                "status",
                "message"
              ],
              "properties": {
                "status": {
                  "type": "integer",
                  "example": 400
                },
                "message": {
                  "type": "string",
                  "example": "Bad request. Validation failed."
                }
              }
            }
          }
        }
      },
      "401": {
        "description": "Unauthorized error",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "required": [
                "status",
                "message",
                "data"
              ],
              "properties": {
                "status": {
                  "type": "integer",
                  "example": 401
                },
                "message": {
                  "type": "string",
                  "example": "Unauthorized"
                },
                "data": {
                  "type": "object",
                  "required": [
                    "message"
                  ],
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "Access token expired"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "404": {
        "description": "Diary not found",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "required": [
                "status",
                "message",
                "data"
              ],
              "properties": {
                "status": {
                  "type": "integer",
                  "example": 404
                },
                "message": {
                  "type": "string",
                  "example": "Diary not found"
                },
                "data": {
                  "type": "null"
                }
              }
            },
            "example": {
              "status": 404,
              "message": "Diary not found",
              "data": null
            }
          }
        }
      },
      "500": {
        "description": "Invalid request payload",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "required": [
                "status",
                "message"
              ],
              "properties": {
                "status": {
                  "type": "integer",
                  "example": 500
                },
                "message": {
                  "type": "string",
                  "example": "Validation failed phoneNumber, contactType, name is required"
                }
              }
            }
          }
        }
      },
      "404-2": {
        "description": "Contact not found",
        "content": {
          "application/json": {
            "schema": {
              "type": "object",
              "required": [
                "status",
                "message"
              ],
              "properties": {
                "status": {
                  "type": "integer",
                  "example": 404
                },
                "message": {
                  "type": "string",
                  "example": "Contact  not found"
                }
              }
            }
          }
        }
      }
    }
  }
}